# Generated by Django 5.0.3 on 2024-04-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_tarefas_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='completa',
            field=models.BooleanField(default=False),
        ),
    ]
